#############################################################################
# Makefile for building: Campus-in-out
# Generated by qmake (2.01a) (Qt 4.8.7) on: Sun Apr 1 23:32:32 2018
# Project:  Campus-in-out.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile Campus-in-out.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtSql -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		account_handler.cpp \
		ui.cpp \
		institute.cpp \
		person.cpp \
		institute_member.cpp \
		security.cpp \
		database_handler.cpp \
		student.cpp \
		worker.cpp \
		faculty.cpp \
		admin.cpp moc_ui.cpp \
		moc_institute.cpp \
		moc_security.cpp \
		moc_admin.cpp
OBJECTS       = main.o \
		account_handler.o \
		ui.o \
		institute.o \
		person.o \
		institute_member.o \
		security.o \
		database_handler.o \
		student.o \
		worker.o \
		faculty.o \
		admin.o \
		moc_ui.o \
		moc_institute.o \
		moc_security.o \
		moc_admin.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Campus-in-out.pro
QMAKE_TARGET  = Campus-in-out
DESTDIR       = 
TARGET        = Campus-in-out

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_ui.h ui_institute.h ui_security.h ui_admin.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Campus-in-out.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtSql.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile Campus-in-out.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtSql.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile Campus-in-out.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Campus-in-out1.0.0 || $(MKDIR) .tmp/Campus-in-out1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Campus-in-out1.0.0/ && $(COPY_FILE) --parents account_handler.h ui.h institute.h person.h institute_member.h security.h database_handler.h student.h worker.h faculty.h admin.h .tmp/Campus-in-out1.0.0/ && $(COPY_FILE) --parents main.cpp account_handler.cpp ui.cpp institute.cpp person.cpp institute_member.cpp security.cpp database_handler.cpp student.cpp worker.cpp faculty.cpp admin.cpp .tmp/Campus-in-out1.0.0/ && $(COPY_FILE) --parents mainwindow.ui ui.ui institute.ui security.ui admin.ui .tmp/Campus-in-out1.0.0/ && (cd `dirname .tmp/Campus-in-out1.0.0` && $(TAR) Campus-in-out1.0.0.tar Campus-in-out1.0.0 && $(COMPRESS) Campus-in-out1.0.0.tar) && $(MOVE) `dirname .tmp/Campus-in-out1.0.0`/Campus-in-out1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Campus-in-out1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_ui.cpp moc_institute.cpp moc_security.cpp moc_admin.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_ui.cpp moc_institute.cpp moc_security.cpp moc_admin.cpp
moc_ui.cpp: ui.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) ui.h -o moc_ui.cpp

moc_institute.cpp: institute.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) institute.h -o moc_institute.cpp

moc_security.cpp: institute_member.h \
		person.h \
		database_handler.h \
		security.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) security.h -o moc_security.cpp

moc_admin.cpp: admin.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) admin.h -o moc_admin.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_ui.h ui_institute.h ui_security.h ui_admin.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_ui.h ui_institute.h ui_security.h ui_admin.h
ui_mainwindow.h: mainwindow.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_ui.h: ui.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic ui.ui -o ui_ui.h

ui_institute.h: institute.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic institute.ui -o ui_institute.h

ui_security.h: security.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic security.ui -o ui_security.h

ui_admin.h: admin.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic admin.ui -o ui_admin.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp ui.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

account_handler.o: account_handler.cpp account_handler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o account_handler.o account_handler.cpp

ui.o: ui.cpp ui.h \
		ui_ui.h \
		institute.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ui.o ui.cpp

institute.o: institute.cpp institute.h \
		ui_institute.h \
		account_handler.h \
		person.h \
		security.h \
		institute_member.h \
		database_handler.h \
		admin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o institute.o institute.cpp

person.o: person.cpp person.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o person.o person.cpp

institute_member.o: institute_member.cpp institute_member.h \
		person.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o institute_member.o institute_member.cpp

security.o: security.cpp security.h \
		institute_member.h \
		person.h \
		database_handler.h \
		ui_security.h \
		student.h \
		account_handler.h \
		worker.h \
		faculty.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o security.o security.cpp

database_handler.o: database_handler.cpp database_handler.h \
		account_handler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o database_handler.o database_handler.cpp

student.o: student.cpp student.h \
		institute_member.h \
		person.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o student.o student.cpp

worker.o: worker.cpp worker.h \
		institute_member.h \
		person.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o worker.o worker.cpp

faculty.o: faculty.cpp faculty.h \
		institute_member.h \
		person.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o faculty.o faculty.cpp

admin.o: admin.cpp admin.h \
		ui_admin.h \
		account_handler.h \
		institute.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o admin.o admin.cpp

moc_ui.o: moc_ui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ui.o moc_ui.cpp

moc_institute.o: moc_institute.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_institute.o moc_institute.cpp

moc_security.o: moc_security.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_security.o moc_security.cpp

moc_admin.o: moc_admin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_admin.o moc_admin.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

